// This file is auto-generated by @hey-api/openapi-ts

export const ExceptionDTOSchema = {
    type: 'object',
    properties: {
        message: {
            type: 'string',
            nullable: true
        },
        stackTrace: {
            type: 'string',
            nullable: true
        }
    },
    additionalProperties: false
} as const;

export const ParameterDTOSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            nullable: true
        },
        parameter_type: {
            type: 'string',
            nullable: true
        },
        variable_name: {
            type: 'string',
            nullable: true
        }
    },
    additionalProperties: false
} as const;

export const StepDTOSchema = {
    required: ['name', 'step_type'],
    type: 'object',
    properties: {
        name: {
            minLength: 1,
            type: 'string'
        },
        description: {
            type: 'string',
            nullable: true
        },
        dependencies: {
            type: 'array',
            items: {
                type: 'string'
            },
            nullable: true
        },
        parameters: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/ParameterDTO'
            },
            nullable: true
        },
        step_type: {
            minLength: 1,
            type: 'string'
        }
    },
    additionalProperties: false
} as const;

export const StepRunDTOSchema = {
    type: 'object',
    properties: {
        step: {
            '$ref': '#/components/schemas/StepDTO'
        },
        variables: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/VariableDTO'
            },
            nullable: true
        },
        generation: {
            type: 'integer',
            format: 'int32'
        },
        status: {
            type: 'string',
            nullable: true
        },
        result: {
            '$ref': '#/components/schemas/VariableDTO'
        },
        exception: {
            '$ref': '#/components/schemas/ExceptionDTO'
        }
    },
    additionalProperties: false
} as const;

export const VariableDTOSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            nullable: true
        },
        type: {
            type: 'string',
            nullable: true
        },
        displayValue: {
            type: 'string',
            nullable: true
        },
        generation: {
            type: 'integer',
            format: 'int32'
        }
    },
    additionalProperties: false
} as const;

export const WorkflowDTOSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            nullable: true
        },
        description: {
            type: 'string',
            nullable: true
        },
        steps: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/StepDTO'
            },
            nullable: true
        }
    },
    additionalProperties: false
} as const;