// This file is auto-generated by @hey-api/openapi-ts

import {
	createClient,
	createConfig,
	type Options,
	formDataBodySerializer,
} from "@hey-api/client-fetch";
import type {
	GetApiV1StepWiseControllerV1GetError,
	GetApiV1StepWiseControllerV1GetResponse,
	GetApiV1StepWiseControllerV1GetStepData,
	GetApiV1StepWiseControllerV1GetStepError,
	GetApiV1StepWiseControllerV1GetStepResponse,
	GetApiV1StepWiseControllerV1GetWorkflowData,
	GetApiV1StepWiseControllerV1GetWorkflowError,
	GetApiV1StepWiseControllerV1GetWorkflowResponse,
	GetApiV1StepWiseControllerV1ListWorkflowError,
	GetApiV1StepWiseControllerV1ListWorkflowResponse,
	GetApiV1StepWiseControllerV1GetConfigurationError,
	GetApiV1StepWiseControllerV1GetConfigurationResponse,
	PostApiV1StepWiseControllerV1ExecuteStepData,
	PostApiV1StepWiseControllerV1ExecuteStepError,
	PostApiV1StepWiseControllerV1ExecuteStepResponse,
	GetBlobByPathData,
	GetBlobByPathError,
	GetBlobByPathResponse,
	GetBlobByUserIdByPathData,
	GetBlobByUserIdByPathError,
	GetBlobByUserIdByPathResponse,
	PostApiV1StepWiseControllerV1SaveCheckpointData,
	PostApiV1StepWiseControllerV1SaveCheckpointError,
	PostApiV1StepWiseControllerV1SaveCheckpointResponse,
	GetApiV1StepWiseControllerV1LoadCheckpointData,
	GetApiV1StepWiseControllerV1LoadCheckpointError,
	GetApiV1StepWiseControllerV1LoadCheckpointResponse,
	DeleteApiV1StepWiseControllerV1DeleteCheckpointData,
	DeleteApiV1StepWiseControllerV1DeleteCheckpointError,
	DeleteApiV1StepWiseControllerV1DeleteCheckpointResponse,
	GetApiV1StepWiseControllerV1ListCheckpointsData,
	GetApiV1StepWiseControllerV1ListCheckpointsError,
	GetApiV1StepWiseControllerV1ListCheckpointsResponse,
	GetApiV1StepWiseControllerV1ExecuteStepSseData,
	GetApiV1StepWiseControllerV1ExecuteStepSseError,
	GetApiV1StepWiseControllerV1ExecuteStepSseResponse,
	PostApiV1StepWiseControllerV1UploadImageData,
	PostApiV1StepWiseControllerV1UploadImageError,
	PostApiV1StepWiseControllerV1UploadImageResponse,
} from "./types.gen";

export const client = createClient(createConfig());

export const getApiV1StepWiseControllerV1Get = <
	ThrowOnError extends boolean = false,
>(
	options?: Options<unknown, ThrowOnError>,
) => {
	return (options?.client ?? client).get<
		GetApiV1StepWiseControllerV1GetResponse,
		GetApiV1StepWiseControllerV1GetError,
		ThrowOnError
	>({
		...options,
		url: "/api/v1/StepWiseControllerV1/Get",
	});
};

export const getApiV1StepWiseControllerV1GetStep = <
	ThrowOnError extends boolean = false,
>(
	options?: Options<GetApiV1StepWiseControllerV1GetStepData, ThrowOnError>,
) => {
	return (options?.client ?? client).get<
		GetApiV1StepWiseControllerV1GetStepResponse,
		GetApiV1StepWiseControllerV1GetStepError,
		ThrowOnError
	>({
		...options,
		url: "/api/v1/StepWiseControllerV1/GetStep",
	});
};

export const getApiV1StepWiseControllerV1GetWorkflow = <
	ThrowOnError extends boolean = false,
>(
	options?: Options<
		GetApiV1StepWiseControllerV1GetWorkflowData,
		ThrowOnError
	>,
) => {
	return (options?.client ?? client).get<
		GetApiV1StepWiseControllerV1GetWorkflowResponse,
		GetApiV1StepWiseControllerV1GetWorkflowError,
		ThrowOnError
	>({
		...options,
		url: "/api/v1/StepWiseControllerV1/GetWorkflow",
	});
};

export const getApiV1StepWiseControllerV1ListWorkflow = <
	ThrowOnError extends boolean = false,
>(
	options?: Options<unknown, ThrowOnError>,
) => {
	return (options?.client ?? client).get<
		GetApiV1StepWiseControllerV1ListWorkflowResponse,
		GetApiV1StepWiseControllerV1ListWorkflowError,
		ThrowOnError
	>({
		...options,
		url: "/api/v1/StepWiseControllerV1/ListWorkflow",
	});
};

export const getApiV1StepWiseControllerV1GetConfiguration = <
	ThrowOnError extends boolean = false,
>(
	options?: Options<unknown, ThrowOnError>,
) => {
	return (options?.client ?? client).get<
		GetApiV1StepWiseControllerV1GetConfigurationResponse,
		GetApiV1StepWiseControllerV1GetConfigurationError,
		ThrowOnError
	>({
		...options,
		url: "/api/v1/StepWiseControllerV1/GetConfiguration",
	});
};

export const postApiV1StepWiseControllerV1ExecuteStep = <
	ThrowOnError extends boolean = false,
>(
	options?: Options<
		PostApiV1StepWiseControllerV1ExecuteStepData,
		ThrowOnError
	>,
) => {
	return (options?.client ?? client).post<
		PostApiV1StepWiseControllerV1ExecuteStepResponse,
		PostApiV1StepWiseControllerV1ExecuteStepError,
		ThrowOnError
	>({
		...options,
		url: "/api/v1/StepWiseControllerV1/ExecuteStep",
	});
};

export const getBlobByPath = <ThrowOnError extends boolean = false>(
	options: Options<GetBlobByPathData, ThrowOnError>,
) => {
	return (options?.client ?? client).get<
		GetBlobByPathResponse,
		GetBlobByPathError,
		ThrowOnError
	>({
		...options,
		url: "/blob/{path}",
	});
};

export const getBlobByUserIdByPath = <ThrowOnError extends boolean = false>(
	options: Options<GetBlobByUserIdByPathData, ThrowOnError>,
) => {
	return (options?.client ?? client).get<
		GetBlobByUserIdByPathResponse,
		GetBlobByUserIdByPathError,
		ThrowOnError
	>({
		...options,
		url: "/blob/{userID}/{path}",
	});
};

export const postApiV1StepWiseControllerV1SaveCheckpoint = <
	ThrowOnError extends boolean = false,
>(
	options?: Options<
		PostApiV1StepWiseControllerV1SaveCheckpointData,
		ThrowOnError
	>,
) => {
	return (options?.client ?? client).post<
		PostApiV1StepWiseControllerV1SaveCheckpointResponse,
		PostApiV1StepWiseControllerV1SaveCheckpointError,
		ThrowOnError
	>({
		...options,
		url: "/api/v1/StepWiseControllerV1/SaveCheckpoint",
	});
};

export const getApiV1StepWiseControllerV1LoadCheckpoint = <
	ThrowOnError extends boolean = false,
>(
	options?: Options<
		GetApiV1StepWiseControllerV1LoadCheckpointData,
		ThrowOnError
	>,
) => {
	return (options?.client ?? client).get<
		GetApiV1StepWiseControllerV1LoadCheckpointResponse,
		GetApiV1StepWiseControllerV1LoadCheckpointError,
		ThrowOnError
	>({
		...options,
		url: "/api/v1/StepWiseControllerV1/LoadCheckpoint",
	});
};

export const deleteApiV1StepWiseControllerV1DeleteCheckpoint = <
	ThrowOnError extends boolean = false,
>(
	options?: Options<
		DeleteApiV1StepWiseControllerV1DeleteCheckpointData,
		ThrowOnError
	>,
) => {
	return (options?.client ?? client).delete<
		DeleteApiV1StepWiseControllerV1DeleteCheckpointResponse,
		DeleteApiV1StepWiseControllerV1DeleteCheckpointError,
		ThrowOnError
	>({
		...options,
		url: "/api/v1/StepWiseControllerV1/DeleteCheckpoint",
	});
};

export const getApiV1StepWiseControllerV1ListCheckpoints = <
	ThrowOnError extends boolean = false,
>(
	options?: Options<
		GetApiV1StepWiseControllerV1ListCheckpointsData,
		ThrowOnError
	>,
) => {
	return (options?.client ?? client).get<
		GetApiV1StepWiseControllerV1ListCheckpointsResponse,
		GetApiV1StepWiseControllerV1ListCheckpointsError,
		ThrowOnError
	>({
		...options,
		url: "/api/v1/StepWiseControllerV1/ListCheckpoints",
	});
};

export const getApiV1StepWiseControllerV1ExecuteStepSse = <
	ThrowOnError extends boolean = false,
>(
	options?: Options<
		GetApiV1StepWiseControllerV1ExecuteStepSseData,
		ThrowOnError
	>,
) => {
	return (options?.client ?? client).get<
		GetApiV1StepWiseControllerV1ExecuteStepSseResponse,
		GetApiV1StepWiseControllerV1ExecuteStepSseError,
		ThrowOnError
	>({
		...options,
		url: "/api/v1/StepWiseControllerV1/ExecuteStepSse",
	});
};

export const postApiV1StepWiseControllerV1UploadImage = <
	ThrowOnError extends boolean = false,
>(
	options?: Options<
		PostApiV1StepWiseControllerV1UploadImageData,
		ThrowOnError
	>,
) => {
	return (options?.client ?? client).post<
		PostApiV1StepWiseControllerV1UploadImageResponse,
		PostApiV1StepWiseControllerV1UploadImageError,
		ThrowOnError
	>({
		...options,
		...formDataBodySerializer,
		headers: {
			"Content-Type": null,
		},
		url: "/api/v1/StepWiseControllerV1/UploadImage",
	});
};
