// This file is auto-generated by @hey-api/openapi-ts

export type ExceptionDTO = {
    message?: (string) | null;
    stackTrace?: (string) | null;
};

export type ParameterDTO = {
    name?: (string) | null;
    parameter_type?: (string) | null;
    variable_name?: (string) | null;
};

export type StepDTO = {
    name: string;
    description?: (string) | null;
    dependencies?: Array<(string)> | null;
    parameters?: Array<ParameterDTO> | null;
    step_type: string;
};

export type StepRunDTO = {
    step?: StepDTO;
    variables?: Array<VariableDTO> | null;
    generation?: number;
    status?: (string) | null;
    result?: VariableDTO;
    exception?: ExceptionDTO;
};

export type VariableDTO = {
    name?: (string) | null;
    type?: (string) | null;
    displayValue?: (string) | null;
    generation?: number;
};

export type WorkflowDTO = {
    name?: (string) | null;
    description?: (string) | null;
    steps?: Array<StepDTO> | null;
};

export type GetApiV1StepWiseControllerV1GetResponse = (unknown);

export type GetApiV1StepWiseControllerV1GetError = unknown;

export type GetApiV1StepWiseControllerV1VersionResponse = (string);

export type GetApiV1StepWiseControllerV1VersionError = unknown;

export type GetApiV1StepWiseControllerV1GetStepData = {
    query?: {
        stepName?: string;
        workflowName?: string;
    };
};

export type GetApiV1StepWiseControllerV1GetStepResponse = (StepDTO);

export type GetApiV1StepWiseControllerV1GetStepError = unknown;

export type GetApiV1StepWiseControllerV1GetWorkflowData = {
    query?: {
        workflowName?: string;
    };
};

export type GetApiV1StepWiseControllerV1GetWorkflowResponse = (WorkflowDTO);

export type GetApiV1StepWiseControllerV1GetWorkflowError = unknown;

export type GetApiV1StepWiseControllerV1ListWorkflowResponse = (Array<WorkflowDTO>);

export type GetApiV1StepWiseControllerV1ListWorkflowError = unknown;

export type PostApiV1StepWiseControllerV1ExecuteStepData = {
    query?: {
        maxParallel?: number;
        maxSteps?: number;
        step?: string;
        workflow?: string;
    };
};

export type PostApiV1StepWiseControllerV1ExecuteStepResponse = (Array<StepRunDTO>);

export type PostApiV1StepWiseControllerV1ExecuteStepError = unknown;

export type GetApiV1StepWiseControllerV1ExecuteStepSseResponse = (unknown);

export type GetApiV1StepWiseControllerV1ExecuteStepSseError = unknown;