// This file is auto-generated by @hey-api/openapi-ts

export type ExceptionDTO = {
	stackTrace?: string | null;
	message: string;
};

export type ParameterDTO = {
	name: string;
	parameter_type: string;
	variable_name: string;
	step_name: string;
	is_configurable_from_web_ui: boolean;
	description: string;
	readonly fullName?: string | null;
};

export type StepDTO = {
	description?: string | null;
	dependencies?: Array<string> | null;
	parameters?: Array<ParameterDTO> | null;
	step_type: string;
	name: string;
};

export type StepRunDTO = {
	step?: StepDTO;
	variables?: Array<VariableDTO> | null;
	result?: VariableDTO;
	exception?: ExceptionDTO;
	generation: number;
	status: string;
};

export type StepWiseImage = {
	url?: string | null;
	name?: string | null;
	content_type?: string | null;
	readonly blob_type?: string | null;
};

export type StepWiseServiceConfiguration = {
	enableAuth0Authentication?: boolean;
	auth0Domain?: string | null;
	auth0ClientId?: string | null;
	auth0Audience?: string | null;
	version?: string | null;
};

export type VariableDTO = {
	value?: unknown;
	displayValue?: string | null;
	name: string;
	type: string;
	generation: number;
};

export type WorkflowDTO = {
	description?: string | null;
	name: string;
	steps: Array<StepDTO>;
};

export type GetApiV1StepWiseControllerV1GetResponse = unknown;

export type GetApiV1StepWiseControllerV1GetError = unknown;

export type GetApiV1StepWiseControllerV1GetStepData = {
	query?: {
		stepName?: string;
		workflowName?: string;
	};
};

export type GetApiV1StepWiseControllerV1GetStepResponse = StepDTO;

export type GetApiV1StepWiseControllerV1GetStepError = unknown;

export type GetApiV1StepWiseControllerV1GetWorkflowData = {
	query?: {
		workflowName?: string;
	};
};

export type GetApiV1StepWiseControllerV1GetWorkflowResponse = WorkflowDTO;

export type GetApiV1StepWiseControllerV1GetWorkflowError = unknown;

export type GetApiV1StepWiseControllerV1ListWorkflowResponse =
	Array<WorkflowDTO>;

export type GetApiV1StepWiseControllerV1ListWorkflowError = unknown;

export type GetApiV1StepWiseControllerV1GetConfigurationResponse =
	StepWiseServiceConfiguration;

export type GetApiV1StepWiseControllerV1GetConfigurationError = unknown;

export type PostApiV1StepWiseControllerV1ExecuteStepData = {
	body?: Array<VariableDTO>;
	query?: {
		maxParallel?: number;
		maxSteps?: number;
		sessionID?: string;
		step?: string;
		workflow?: string;
	};
};

export type PostApiV1StepWiseControllerV1ExecuteStepResponse =
	Array<StepRunDTO>;

export type PostApiV1StepWiseControllerV1ExecuteStepError = unknown;

export type GetBlobByPathData = {
	path: {
		path: string;
	};
};

export type GetBlobByPathResponse = unknown;

export type GetBlobByPathError = unknown;

export type GetBlobByUserIdByPathData = {
	path: {
		path: string;
		userID: string;
	};
};

export type GetBlobByUserIdByPathResponse = unknown;

export type GetBlobByUserIdByPathError = unknown;

export type PostApiV1StepWiseControllerV1SaveCheckpointData = {
	body?: Array<StepRunDTO>;
	query?: {
		checkpointName?: string;
		workflow?: string;
	};
};

export type PostApiV1StepWiseControllerV1SaveCheckpointResponse = string;

export type PostApiV1StepWiseControllerV1SaveCheckpointError = unknown;

export type GetApiV1StepWiseControllerV1LoadCheckpointData = {
	query?: {
		checkpointName?: string;
		workflow?: string;
	};
};

export type GetApiV1StepWiseControllerV1LoadCheckpointResponse =
	Array<StepRunDTO>;

export type GetApiV1StepWiseControllerV1LoadCheckpointError = unknown;

export type DeleteApiV1StepWiseControllerV1DeleteCheckpointData = {
	query?: {
		checkpointName?: string;
		workflow?: string;
	};
};

export type DeleteApiV1StepWiseControllerV1DeleteCheckpointResponse = unknown;

export type DeleteApiV1StepWiseControllerV1DeleteCheckpointError = unknown;

export type GetApiV1StepWiseControllerV1ListCheckpointsData = {
	query?: {
		workflow?: string;
	};
};

export type GetApiV1StepWiseControllerV1ListCheckpointsResponse = Array<string>;

export type GetApiV1StepWiseControllerV1ListCheckpointsError = unknown;

export type GetApiV1StepWiseControllerV1ExecuteStepSseData = {
	query?: {
		sessionID?: string;
	};
};

export type GetApiV1StepWiseControllerV1ExecuteStepSseResponse = unknown;

export type GetApiV1StepWiseControllerV1ExecuteStepSseError = unknown;

export type PostApiV1StepWiseControllerV1UploadImageData = {
	body?: {
		image?: Blob | File;
	};
};

export type PostApiV1StepWiseControllerV1UploadImageResponse = StepWiseImage;

export type PostApiV1StepWiseControllerV1UploadImageError = unknown;
